### ISSUE TITLE
Problem do not uninstall cleanly

### ISSUE THREAD

**Issue by ddcc** [picoCTF/picoCTF-shell-manager#11]
After uninstalling a problem, the created user instances for the problems still remain, including the contents of their home directories.

**Comment by cganas** [comment]
I think there is a misconception about what you mean by "uninstalling" a problem. If you have used apt to uninstall the problem package what you have really done is uninstalled the source for the problem. Shell manager will no longer be able to **deploy** that problem; however, in no way does this intend to remove the deployed instances.

Something that should be reinforced in our notes/documentation is the abstraction of a problem instance from the problem source.

It would be useful instead to create an issue concerning the removal of deployed problem instances. We can not guarantee the completeness of this procedure as the challenge.py's permit any setup; however, in most cases, we can cleanly remove instances from the shell server.
