### ISSUE TITLE
Securing the User Shell Environment

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-shell-manager#18]
As it stands we have no resource limits put in place for users on the shell server. Some of the restrictions from last year are included below.

```
chmod a-s /usr/bin/wall /usr/bin/bsd-write /usr/bin/at
chmod a-s /usr/bin/passwd /usr/bin/gpasswd /usr/bin/chfn
find / -perm +6000 -type f -a \( -group mail -o -group shadow \) -exec chmod a-s {} \; 2> /dev/null

chmod o-rwx /var/log/lastlog /var/log/wtmp /var/log/btmp /var/run/utmp /run/utmp

# Setup limits.
cat >> /etc/security/limits.conf<<EOF
@picogroup hard as 512000
@picogroup hard nproc 50
EOF

cat > /etc/sysctl.conf <<EOF
#disable ASLR
kernel.randomize_va_space = 0
# Disable YAMA ptrace restrictions.
kernel.yama.ptrace_scope = 0
EOF

# Commit
sysctl -p

# Prevent users from seeing each other's processes.
mount -o remount,hidepid=2,gid=1000 /proc
cat > /etc/rc.local <<EOF
#!/bin/sh -e
mount -o remount,hidepid=2,gid=1000 /proc
exit 0
EOF


# Prevent people from seeing each other's files in tmp dirs.
chmod 1733 /tmp /var/tmp /dev/shm
```

**Comment by royragsdale** [comment]
Agree that we should secure the shell-server environment as well as implement limits and rules that isolate competitors.

Another example of this is PR #14 where crashes would log potentially advantageous information.

I believe the right place to include this type of configuration is in [picoCTF-platform](https://github.com/picoCTF/picoCTF-platform) as we standardize that repo as the place where all elements are pulled together in a fully functioning and configured deployment.

**Comment by cganas** [comment]
This has been moved to https://github.com/picoCTF/picoCTF-platform/pull/9
