### ISSUE TITLE
Instance IDs should not be predictable

### ISSUE THREAD

**Issue by ethan42** [picoCTF/picoCTF-shell-manager#29]
Different instances of the same problem should not be predictable, since in some challenges simply diff'ing the files from the two instances is enough to reveal the key.

The suggestion is to convert the "_<increasing_num>" suffixes in the paths/users by "_<unpredictable_hash>".

**Comment by cganas** [comment]
As discussed we don't have a perfect solution without groups as clever users can still figure out where the other instances are located; however, it is now more trouble to determine. :)

**Comment by ethan42** [comment]
It seems that making the challenge deployment directory different from the user's HOME directory would resolve this issue.

**Comment by tim-becker** [comment]
Yes, that could work, but we lose the neat benefits of having the challenges be in their home directories. Overall, I still think it would be worth it to make this change, and it wouldn't be very complex code-wise.

I guess the next question is: where do we want to store the instance directories?

**Comment by ethan42** [comment]
Perhaps under a common /problems directory? We've also tried that before.

**Comment by cganas** [comment]
It is worth noting that the completion of picoCTF/picoCTF-web#7 would solve this issue (with the addition of groups) for almost free without having to change the instance home directory assumption.

Maintaining a set of groups is no more difficult than maintaining a set of active symlinks. In addition, we would not have to obfuscate anything as we would have access control

**Comment by ethan42** [comment]
By the way, if you put all problems under a shared /problems directory, you could remove HOME directories altogether from problem users.

Using groups on top would be nice. However, I am a bit skeptical about the complexity of maintaining consistency between the website progress and the shell server.

**Comment by cganas** [comment]
That's true, the additional complexity is daunting. However, I'm not sure if it is something we can avoid in the long term. Either group permissions (afaik the only **real** solution) or symlinks will require a web daemon to manage it.

And from what we observed during the competition people will symlink annoying directory names. :P
