### ISSUE TITLE
Problem Service Managers

### ISSUE THREAD

**Issue by cganas** [picoCTF/picoCTF-shell-manager#41]
This is currently a stub. It does not contain information about our current setup.

Additionally, this issue can be used as a forum of discussion concerning alternatives to systemd as our primary problem service manager.

**Comment by ethan42** [comment]
I recommend xinetd as a possible alternative. We have used it on multiple occasions successfully and has a relatively small overhead. The tooling required would be similar to what is needed for systemd (one configuration file per service).

**Comment by jedav** [comment]
I have also heard [runit](http://smarden.org/runit/) and [s6](http://skarnet.org/software/s6/) mentioned as superior systemd alternatives in some contexts.

**Comment by tim-becker** [comment]
Update: Since PR #58, we are more dependent than ever on systemd, and it seems to be fairly stable. Changing service managers at this points would be a large chunk of work, so unless there are still strong feelings against systemd, I think we can close this issue.
