### ISSUE TITLE
FlaskApp problems and multiple gunicorn instances

### ISSUE THREAD

**Issue by tylerni7** [picoCTF/picoCTF-shell-manager#44]
Currently in picoCTF-shell-manager/hacksport/problem.py when a FlaskApp problem is created, one gunicorn instance is launched. For larger competitions this may not be sufficient.

When more instances are created, there are some issues with things like making sure the application secret key agrees across all instances (since problem authors likely just use os.urandom to generate a secret key). 

I would suggest we have multiple workers (perhaps a configurable amount as a variable in a FlaskApp instance), and that the hacksport problem API handles dealing with the app keys, as most FlaskApps should have random, secret app keys.

**Comment by cganas** [comment]
Oh! I misunderstood what you meant in Slack. This is something we should definitely handle. Thanks for bringing it to my attention.

**Comment by tim-becker** [comment]
Addressed in 4a933fdfebf6d4cbfefc2c9e4ef6a6ce5b74a420
