### ISSUE TITLE
socat services can be killed/port squatted

### ISSUE THREAD

**Issue by rickyz** [picoCTF/picoCTF-shell-manager#55]
This won't be an issue with nice competitors, but currently, remote services appear to run the socat command as the user. This means that the port is bound as the service user, so someone who gets a shell on a remote service can kill socat and steal the port, or probably DoS the service by sending socat SIGSTOP. It might be worth using xinetd or systemd's replacement to avoid this issue.

Worth noting that even after fixing this, it's hard to stop a determined saboteur from disrupting the service by killing it in a loop without doing PID namespace trickery, so maybe the marginal gain from fixing the socat process's user isn't worth it? Up to you :-)

**Comment by tim-becker** [comment]
Thanks for pointing this out. Coincidentally, I'm currently working on switching the services over to using systemd socket activation, so this issue (at least the first one) should be resolved shortly.

**Comment by tim-becker** [comment]
Closed by #58 .
