### ISSUE TITLE
Security issue with useradd commands

### ISSUE THREAD

**Issue by eugenekolo** [picoCTF/picoCTF-shell-manager#81]
A user can be registered with the username "sudo", receive the default group of their username, "sudo", and have sudo access.  This is particularly bad on Ubuntu server which default enables sudoers group.

```
subprocess.check_output(["/usr/sbin/useradd", "-m", "-G", COMPETITORS_GROUP, "-s", "/bin/bash", user])
```
```
execute(["useradd", "-s", "/bin/bash", username])
```

The fix is to add -N:
> -N, --no-user-group
           Do not create a group with the same name as the user, but add the user to the group specified by the -g option or by the GROUP variable in /etc/default/useradd.

https://github.com/picoCTF/picoCTF-shell-manager/blob/8fac73afce547802252470b96683c389a5ac3ebe/hacksport/operations.py#L58
https://github.com/picoCTF/picoCTF-shell-manager/blob/0501b67fb4716e9fb8d3fe956c45bbacb4ceaeb3/config/pam_auth.py#L88

**Comment by cganas** [comment]
Hey! This is a great find. There are a few issues with the way we create shell accounts but this deserves immediate attention.

I was able to reproduce the issue and believe `subprocess.check_output(["/usr/sbin/useradd", "-m", "-N", "-g", COMPETITORS_GROUP, "-s", "/bin/bash", user])` will leave us with something similar to `uid=1147(test) gid=1002(competitors) groups=1002(competitors)`.

I'm still not sure what the best way to blacklist a set of usernames is for a few reasons. I also don't believe it to be sufficient. It's hard to create an exhaustive list of users; the most obvious protection is to disallow the creation of usernames that have real shell accounts associated with it. That protection is still susceptible to your attack provided this fix is not in place. And there is no particularly great way of getting up-to-date information to the web server for user registration.

So it's something we're still looking at. But your tip is most appreciated. :tada:

**Comment by cganas** [comment]
I'm going to close this for now but if you have any other suggestions I would be happy to hear them.

Another solution would be to hash the username for the group name. This doesn't prevent the less dangerous but equally infuriating issue of creating an account with a username of an already existing username on the shell server which prevents you from logging in, e.g. web user root goes to the shell page and tries to login but the user already exists (and isn't in the competitors group) so we drop back to non-PAM auth.
